### ISSUE TITLE
Latest version of agora is not working is gives me No identifiers allowed directly ater numeric litreal, stack:

### ISSUE THREAD

**Issue by Dhaval1905** [AgoraIO-Extensions/react-native-agora#846]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by guoxianzhe** [comment]
@Dhaval1905 Sorry, I can not reproduce this with clean react-native app, can you give me more details?

**Comment by vijay14887** [comment]
I am also facing this issue in Android. Could you please help?

**Comment by vijay14887** [comment]
Full Error - error node_modules/react-native-agora/src/Utils.ts: Unexpected token name «n», expected punc «,» in file node_modules/react-native-agora/src/Utils.ts at 9:32.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 26s

    at makeError (/Users/vijay/Desktop/react-native/DoctorRN/node_modules/execa/index.js:174:9)
    at /Users/vijay/Desktop/react-native/DoctorRN/node_modules/execa/index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (/Users/vijay/Desktop/react-native/DoctorRN/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/vijay/Desktop/react-native/DoctorRN/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details.
 when I run the command - npx react-native run-android --variant=release
